name: app
version: 1.1.1+10
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  advance_pdf_viewer_fork: 2.0.0
  audioplayers: ^4.1.0
  cached_network_image: 3.2.3
  cupertino_icons: ^1.0.2
  date_time_picker: 2.1.0
  device_info_plus: ^9.0.2
  dio: ^5.2.1+1
  dotted_border: 2.0.0+3
  downloads_path_provider_28: 0.1.2
  easy_refresh: ^3.3.2+1
  # firebase_analytics: 
  firebase_core: ^2.14.0
  firebase_messaging: ^14.6.3
  fl_chart: ^0.63.0
  fl_country_code_picker: 0.0.4
  flutter:
    sdk: flutter
  flutter_linkify: ^6.0.0
  flutter_local_notifications: ^14.1.1
  flutter_screenutil: 5.8.4
  flutter_svg: ^2.0.7
  flutter_widget_from_html_core: ^0.10.1
  get: 4.6.5
  get_ip_address: 0.0.5
  get_storage: ^2.1.1
  iconify_flutter:
    git: https://github.com/pnghai/iconify_flutter.git
  image_picker: ^0.8.9
  just_the_tooltip: 0.0.12
  laravel_echo:
    git:
      url: https://github.com/kakajansh/echo.git
      ref: master
  money_formatter: 0.0.3
  open_store: 0.5.0
  otp_text_field: 1.1.3
  overlay_support: 2.1.0
  permission_handler: ^10.3.0
  persian_number_utility: ^1.1.3
  phone_numbers_parser: 7.0.2
  phone_text_field: ^0.0.3
  pusher_client:
    git:
      url: https://github.com/DumbDev168/pusher_client.git
      ref: master
  shimmer: ^3.0.0
  timezone: ^0.9.2
  url_launcher: ^6.1.11
  webview_flutter: ^4.2.2

dev_dependencies:
  build_runner: 2.4.5
  flutter_gen_runner: 5.3.1
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

# dependency_overrides:
#   iconify_flutter:
#     git: https://github.com/pnghai/iconify_flutter.git
flutter_icons:
  android: launcher_icon
  image_path: assets/images/png/logo-app-2.png
  ios: true
  min_sdk_android: 21

flutter_gen:
  output: lib/generated
  integrations:
    flutter_svg: true
    flare_flutter: false
    rive: false
  line_length: 80

flutter:
  assets:
    - assets/translations/
    - assets/fonts/
    - assets/images/png/
    - assets/images/svg/
    - assets/sounds/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter/Inter-Black.ttf
          weight: 900
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal/Tajawal-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Tajawal/Tajawal-Light.ttf
          weight: 300
        - asset: assets/fonts/Tajawal/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/fonts/Tajawal/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/Tajawal/Tajawal-Bold.ttf
          weight: 600
        - asset: assets/fonts/Tajawal/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/fonts/Tajawal/Tajawal-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Tajawal/Tajawal-Black.ttf
          weight: 900
  uses-material-design: true
