name: app
version: 1.0.5+5
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.5 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  date_time_picker: 2.1.0
  dotted_border: 2.0.0+3
  # extended_phone_number_input: 1.0.2
  fl_country_code_picker: 0.0.4
  flutter_screenutil: 5.6.0
  flutter_svg: 1.1.6
  iconify_flutter: 0.0.5
  just_the_tooltip: 0.0.12
  shimmer: 2.0.0
  get_storage: 2.0.3
  image_picker: 0.8.6
  firebase_core: 2.4.1
  firebase_messaging: 14.2.1
  flutter_local_notifications: 13.0.0
  overlay_support: 2.1.0
  otp_text_field: 1.1.3
  cached_network_image: 3.2.3
  device_info_plus: 8.0.0
  get_ip_address: 0.0.5
  fl_chart: 0.55.2
  money_formatter: 0.0.3
  timezone: 0.9.1
  advance_pdf_viewer_fork: 2.0.0
  flutter_widget_from_html_core: 0.9.1
  webview_flutter: 4.0.2
  audioplayers: 3.0.1
  # path_provider: 2.0.12
  permission_handler: 10.2.0
  # open_file: 3.1.0
  # universal_html: 2.0.8
  easy_refresh: 3.3.0+1
  dio: 5.0.0
  image_downloader: 0.31.0
  downloads_path_provider_28: 0.1.2
  open_store: 0.5.0
  flutter_linkify: 5.0.2
  url_launcher: 6.1.10
  # flutter_widget_from_html: 0.9.1
  phone_text_field: 0.0.1
  phone_numbers_parser: 7.0.2

  laravel_echo:
      git:
        url: https://github.com/kakajansh/echo.git
        ref: master
  pusher_client:
      git:
        url: https://github.com/DumbDev168/pusher_client.git
        ref: master
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  build_runner: 2.3.3
  flutter_launcher_icons: "^0.11.0"
  flutter_gen_runner: 5.1.0+1
  flutter_test: 
    sdk: flutter

flutter_icons: 
  android: launcher_icon
  image_path: assets/images/png/logo-app-2.png
  ios: true
  min_sdk_android: 21

flutter_gen: 
  output: lib/generated
  integrations: 
    flutter_svg: true
    flare_flutter: false
    rive: false
  line_length: 80

flutter: 
  assets: 
    - assets/translations/
    - assets/fonts/
    - assets/images/png/
    - assets/images/svg/
    - assets/sounds/
  fonts: 
    - family: Inter
      fonts: 
        - asset: assets/fonts/Inter/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Inter/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter/Inter-Black.ttf
          weight: 900
    - family: Tajawal
      fonts: 
        - asset: assets/fonts/Tajawal/Tajawal-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Tajawal/Tajawal-Light.ttf
          weight: 300
        - asset: assets/fonts/Tajawal/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/fonts/Tajawal/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/Tajawal/Tajawal-Bold.ttf
          weight: 600
        - asset: assets/fonts/Tajawal/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/fonts/Tajawal/Tajawal-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Tajawal/Tajawal-Black.ttf
          weight: 900
  uses-material-design: true

